name: We Enjoy
url: https://we-enjoy.us
permalink: pretty
paginate: 10
paginate_path: "page/:num"
markdown: kramdown
exclude:
  - .env
  - README.md
  - _tumblr.json
  - _twitter.json
  - node_modules
  - package.json
  - webpack.config.js
  - bin
  - assets/_
sass:
  style: compressed
plugins: [jekyll-paginate]
