name: We Enjoy
url: https://we-enjoy.us
permalink: pretty
paginate: 10
paginate_path: "page/:num"
markdown: kramdown
exclude:
  - .env
  - CNAME
  - README.md
  - _tumblr.json
  - _twitter.json
  - bin
  - bower.json
  - bower_components
  - node_modules
  - package.json
  - webpack.config.js
sass:
  style: compressed
image:
  width: 800
  height: 400
gems: [jekyll-paginate]
