name: We Enjoy
url: //we-enjoy.us
# url: http://localhost:4000
permalink: pretty
paginate: 10
paginate_path: "page/:num"
markdown: kramdown
exclude:
  - bin
  - README.md
  - CNAME
  - _tumblr.json
  - _twitter.json
  - node_modules
  - bower_components
sass:
  style: compressed
image:
  width: 800
  height: 400
gems: [jekyll-paginate]
